# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FingerprintProtocol.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x46ingerprintProtocol.proto\x12\ntextsecure\"9\n\x12LogicalFingerprint\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\x12\x12\n\nidentifier\x18\x02 \x01(\x0c\"\x9c\x01\n\x14\x43ombinedFingerprints\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x38\n\x10localFingerprint\x18\x02 \x01(\x0b\x32\x1e.textsecure.LogicalFingerprint\x12\x39\n\x11remoteFingerprint\x18\x03 \x01(\x0b\x32\x1e.textsecure.LogicalFingerprintB=\n(org.whispersystems.libsignal.fingerprintB\x11\x46ingerprintProtos')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FingerprintProtocol_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n(org.whispersystems.libsignal.fingerprintB\021FingerprintProtos'
  _LOGICALFINGERPRINT._serialized_start=41
  _LOGICALFINGERPRINT._serialized_end=98
  _COMBINEDFINGERPRINTS._serialized_start=101
  _COMBINEDFINGERPRINTS._serialized_end=257
# @@protoc_insertion_point(module_scope)
