CREATE_ACCOUNT_SMS_PATH = "/v1/accounts/sms/code/%s?client=%s"
CREATE_ACCOUNT_VOICE_PATH = "/v1/accounts/voice/code/%s"
VERIFY_ACCOUNT_CODE_PATH = "/v1/accounts/code/%s"
REGISTER_GCM_PATH = "/v1/accounts/gcm/"
TURN_SERVER_INFO = "/v1/accounts/turn"
SET_ACCOUNT_ATTRIBUTES = "/v1/accounts/attributes/"
PIN_PATH = "/v1/accounts/pin/"
REQUEST_PUSH_CHALLENGE = "/v1/accounts/fcm/preauth/%s/%s"
WHO_AM_I = "/v1/accounts/whoami"

PREKEY_METADATA_PATH = "/v2/keys/"
PREKEY_PATH = "/v2/keys/%s"
PREKEY_DEVICE_PATH = "/v2/keys/%s/%s"
SIGNED_PREKEY_PATH = "/v2/keys/signed"

PROVISIONING_CODE_PATH = "/v1/devices/provisioning/code"
PROVISIONING_MESSAGE_PATH = "/v1/provisioning/%s"
DEVICE_PATH = "/v1/devices/%s"
DEVICES_PATH = "/v1/devices"

DIRECTORY_TOKENS_PATH = "/v1/directory/tokens"
DIRECTORY_VERIFY_PATH = "/v1/directory/%s"
DIRECTORY_AUTH_PATH = "/v2/directory/auth"
DIRECTORY_FEEDBACK_PATH = "/v1/directory/feedback-v3/%s"
MESSAGE_PATH = "/v1/messages/%s"
SENDER_ACK_MESSAGE_PATH = "/v1/messages/%s/%d"
UUID_ACK_MESSAGE_PATH = "/v1/messages/uuid/%s"
ATTACHMENT_PATH = "/v2/attachments/form/upload"

PROFILE_PATH = "/v1/profile/%s"
KEEPALIVE_PATH = "/v1/keepalive"
